spring.application.name=NotificationServer

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

app.telegram.token=${TELEGRAM_TOKEN}
app.telegram.account_id=${TELEGRAM_ACCOUNT_ID}